# Generated by Django 4.2 on 2023-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('saiga', models.IntegerField()),
                ('red_book', models.IntegerField()),
                ('others', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TakenItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saiga_without_horns', models.IntegerField()),
                ('saiga_with_horns', models.IntegerField()),
                ('saiga_female', models.IntegerField()),
                ('horns', models.IntegerField()),
                ('segoltok', models.IntegerField()),
                ('arhar', models.IntegerField()),
                ('jeiran', models.IntegerField()),
                ('drofa', models.IntegerField()),
                ('qulan', models.IntegerField()),
                ('sadja', models.IntegerField()),
                ('falcon', models.IntegerField()),
                ('podorlik', models.IntegerField()),
                ('falcon_baloban', models.IntegerField()),
                ('sturgeon', models.IntegerField()),
                ('badger', models.IntegerField()),
            ],
        ),
    ]
