# Generated by Django 4.2 on 2023-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_crimenumber_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimenumber',
            name='percentage',
            field=models.FloatField(default=0.01, max_length=3),
            preserve_default=False,
        ),
    ]
