# Generated by Django 4.2 on 2023-05-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_location_takenitems_year_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='location',
        ),
        migrations.AddField(
            model_name='animal',
            name='region',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='year',
            field=models.IntegerField(default=2001),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
