# Generated by Django 4.2 on 2023-05-06 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_alter_animal_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=500)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.animaldata')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.AddField(
            model_name='animalname',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.location'),
        ),
    ]
